# Generated by Powerlevel10k configuration wizard on 2023-09-22 at 20:08 -05.
# Based on romkatv/powerlevel10k/config/p10k-rainbow.zsh, checksum 42599.
# Wizard options: nerdfont-complete + powerline, small icons, rainbow, unicode,
# round separators, round heads, flat tails, 1 line, sparse, many icons, concise,
# transient_prompt, instant_prompt=quiet.
# Type `p10k configure` to generate another config.
#
# Config for Powerlevel10k with powerline prompt style with colorful background.
# Type `p10k configure` to generate your own config based on it.

# Temporarily change options.
'builtin' 'local' '-a' 'p10k_config_opts'
[[ ! -o 'aliases'         ]] || p10k_config_opts+=('aliases')
[[ ! -o 'sh_glob'         ]] || p10k_config_opts+=('sh_glob')
[[ ! -o 'no_brace_expand' ]] || p10k_config_opts+=('no_brace_expand')
'builtin' 'setopt' 'no_aliases' 'no_sh_glob' 'brace_expand'

() {
  emulate -L zsh -o extended_glob

  # Unset all configuration options. This allows you to apply configuration changes without
  # restarting zsh. Edit ~/.p10k.zsh and type `source ~/.p10k.zsh`.
  unset -m '(POWERLEVEL9K_*|DEFAULT_USER)~POWERLEVEL9K_GITSTATUS_DIR'

  # Zsh >= 5.1 is required.
  [[ $ZSH_VERSION == (5.<1->*|<6->.*) ]] || return

  # Paleta de colores rojizos estilo ThinkPad
  typeset -g POWERLEVEL9K_OS_ICON_FOREGROUND=230  # Blanco crema
  typeset -g POWERLEVEL9K_OS_ICON_BACKGROUND=160   # Rojo ThinkPad clásico

  typeset -g POWERLEVEL9K_DIR_FOREGROUND=230       # Blanco crema
  typeset -g POWERLEVEL9K_DIR_BACKGROUND=88        # Rojo oscuro
  typeset -g POWERLEVEL9K_DIR_SHORTENED_FOREGROUND=180
  typeset -g POWERLEVEL9K_DIR_ANCHOR_FOREGROUND=255

  typeset -g POWERLEVEL9K_STATUS_OK_FOREGROUND=230
  typeset -g POWERLEVEL9K_STATUS_OK_BACKGROUND=88
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_FOREGROUND=230
  typeset -g POWERLEVEL9K_STATUS_OK_PIPE_BACKGROUND=88

  typeset -g POWERLEVEL9K_STATUS_ERROR_FOREGROUND=230
  typeset -g POWERLEVEL9K_STATUS_ERROR_BACKGROUND=160
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_FOREGROUND=230
  typeset -g POWERLEVEL9K_STATUS_ERROR_SIGNAL_BACKGROUND=160
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_FOREGROUND=230
  typeset -g POWERLEVEL9K_STATUS_ERROR_PIPE_BACKGROUND=160

  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FOREGROUND=230
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_BACKGROUND=90

  typeset -g POWERLEVEL9K_CONTEXT_ROOT_FOREGROUND=230
  typeset -g POWERLEVEL9K_CONTEXT_ROOT_BACKGROUND=166  # Naranja-rojizo
  typeset -g POWERLEVEL9K_CONTEXT_FOREGROUND=180
  typeset -g POWERLEVEL9K_CONTEXT_BACKGROUND=0

  typeset -g POWERLEVEL9K_VCS_CLEAN_BACKGROUND=22      # Verde oscuro para contraste
  typeset -g POWERLEVEL9K_VCS_MODIFIED_BACKGROUND=130  # Naranja-rojizo
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_BACKGROUND=52  # Rojo vino
  typeset -g POWERLEVEL9K_VCS_CONFLICTED_BACKGROUND=130
  typeset -g POWERLEVEL9K_VCS_LOADING_BACKGROUND=8

  # Prompt Elements (manteniendo tu configuración original)
  typeset -g POWERLEVEL9K_LEFT_PROMPT_ELEMENTS=(
    os_icon
    dir
    status
    command_execution_time
    context
  )

  typeset -g POWERLEVEL9K_RIGHT_PROMPT_ELEMENTS=(
    # (todos los elementos originales comentados se mantienen igual)
  )

  # Configuración de iconos y separadores (sin cambios)
  typeset -g POWERLEVEL9K_MODE=nerdfont-complete
  typeset -g POWERLEVEL9K_ICON_PADDING=none
  typeset -g POWERLEVEL9K_PROMPT_ADD_NEWLINE=true

  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_PREFIX='%242F╭─'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_PREFIX='%242F├─'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_PREFIX='%242F╰─'
  typeset -g POWERLEVEL9K_MULTILINE_FIRST_PROMPT_SUFFIX='%242F─╮'
  typeset -g POWERLEVEL9K_MULTILINE_NEWLINE_PROMPT_SUFFIX='%242F─┤'
  typeset -g POWERLEVEL9K_MULTILINE_LAST_PROMPT_SUFFIX='%242F─╯'

  typeset -g POWERLEVEL9K_LEFT_SUBSEGMENT_SEPARATOR='\uE0B5'
  typeset -g POWERLEVEL9K_RIGHT_SUBSEGMENT_SEPARATOR='\uE0B7'
  typeset -g POWERLEVEL9K_LEFT_SEGMENT_SEPARATOR='\uE0B4'
  typeset -g POWERLEVEL9K_RIGHT_SEGMENT_SEPARATOR='\uE0B6'

  # Configuración de caracteres de prompt (sin cambios)
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OK_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=208
  typeset -g POWERLEVEL9K_PROMPT_CHAR_ERROR_{VIINS,VICMD,VIVIS,VIOWR}_FOREGROUND=196
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIINS_CONTENT_EXPANSION='❯'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VICMD_CONTENT_EXPANSION='❮'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIVIS_CONTENT_EXPANSION='V'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_{OK,ERROR}_VIOWR_CONTENT_EXPANSION='▶'
  typeset -g POWERLEVEL9K_PROMPT_CHAR_OVERWRITE_STATE=true

  # Configuración de iconos específicos (sin cambios)
  typeset -g POWERLEVEL9K_VCS_BRANCH_ICON='\uF126 '
  typeset -g POWERLEVEL9K_VCS_UNTRACKED_ICON='?'
  typeset -g POWERLEVEL9K_VCS_INCOMING_CHANGES_ICON='\uf0ab '
  typeset -g POWERLEVEL9K_VCS_OUTGOING_CHANGES_ICON='\uf0aa '
  typeset -g POWERLEVEL9K_VCS_STASH_ICON='\uf01c '

  # Configuraciones varias (sin cambios)
  typeset -g POWERLEVEL9K_VCS_MAX_INDEX_SIZE_DIRTY=-1
  typeset -g POWERLEVEL9K_VCS_DISABLED_WORKDIR_PATTERN='~'
  typeset -g POWERLEVEL9K_VCS_DISABLE_GITSTATUS_FORMATTING=true
  typeset -g POWERLEVEL9K_VCS_CONTENT_EXPANSION='${$((my_git_formatter()))+${my_git_format}}'
  typeset -g POWERLEVEL9K_VCS_{STAGED,UNSTAGED,UNTRACKED,CONFLICTED,COMMITS_AHEAD,COMMITS_BEHIND}_MAX_NUM=-1

  # Configuración de tiempo de ejecución (sin cambios)
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_THRESHOLD=3
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_PRECISION=0
  typeset -g POWERLEVEL9K_COMMAND_EXECUTION_TIME_FORMAT='d h m s'

  # Configuración de transient prompt (sin cambios)
  typeset -g POWERLEVEL9K_TRANSIENT_PROMPT=always
  typeset -g POWERLEVEL9K_INSTANT_PROMPT=quiet
  typeset -g POWERLEVEL9K_DISABLE_HOT_RELOAD=true

  # Si p10k ya está cargado, recargar configuración
  (( ! $+functions[p10k] )) || p10k reload
}

# Tell `p10k configure` which file it should overwrite.
typeset -g POWERLEVEL9K_CONFIG_FILE=${${(%):-%x}:a}

(( ${#p10k_config_opts} )) && setopt ${p10k_config_opts[@]}
'builtin' 'unset' 'p10k_config_opts'